//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGTPPE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETS
    {
        public int idTickets { get; set; }
        public string emplacementMaterielTicket { get; set; }
        public string typeMaterielTicket { get; set; }
        public Nullable<int> niveauUrgenceTicket { get; set; }
        public string descriptionIncident { get; set; }
        public Nullable<System.DateTime> dateCreationTicket { get; set; }
        public Nullable<System.DateTime> dateClotureTicket { get; set; }
        public Nullable<int> idUtilisateur { get; set; }
        public string numeroSerieMateriel { get; set; }
    
        public virtual MATERIEL MATERIEL { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
    }
}
